require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WineAppsController do

  # This should return the minimal set of attributes required to create a valid
  # WineApp. As you add validations to WineApp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {:name => "this name"  } }
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WineAppsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "exposes all wine_apps as @wine_apps" do
      test_wine_app = WineApp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wine_apps).should eq([test_wine_app])
    end
  end

  describe "GET show" do
    it "assigns the requested wine_app as @wine_app" do
      wine_app = WineApp.create! valid_attributes
      get :show, {:id => wine_app.to_param}, valid_session
      assigns(:wine_app).should eq(wine_app)
    end
  end

  describe "GET new" do
    it "exposes a new WineApp instance as wine_app" do
      get :new, {}, valid_session
      assigns(:wine_app).should be_a_new(WineApp)
    end
  end

  describe "GET edit" do
    it "exposes the requested wine_app as wine_app" do
      wine_app = WineApp.create! valid_attributes
      get :edit, { :id => wine_app.to_param }, valid_session
      assigns(:wine_app).should eq(wine_app)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WineApp" do
        expect {
          post :create, {:wine_app => valid_attributes}, valid_session
        }.to change(WineApp, :count).by(1)
      end

      it "exposes a newly created wine_app as wine_app" do
        post :create, {:wine_app => valid_attributes}, valid_session
        assigns(:wine_app).should be_a(WineApp)
        assigns(:wine_app).should be_persisted
      end

      it "redirects to the created wine_app" do
        post :create, {:wine_app => valid_attributes}, valid_session
        expect(response).to redirect_to(WineApp.last)
      end
    end

    describe "with invalid params" do
      it "exposes a newly created but unsaved wine_app as @wine_app" do
        # Trigger the behavior that occurs when invalid params are submitted
        WineApp.any_instance.stub(:save).and_return(false)
        post :create, {:wine_app => { name: nil  }}, valid_session
        assigns(:wine_app).should be_a_new(WineApp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WineApp.any_instance.stub(:save).and_return(false)
        post :create, {:wine_app => { name: nil }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wine_app" do
        wine_app = WineApp.create! valid_attributes
        # Assuming there are no other wine_apps in the database, this
        # specifies that the WineApp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WineApp.any_instance.should_receive(:update).with({"name" => "this name"})
        put :update, {:id => wine_app.to_param, :wine_app => {"name" => "this name"}}, valid_session
      end

      it "assigns the requested wine_app as @wine_app" do
        wine_app = WineApp.create! valid_attributes
        put :update, {:id => wine_app.to_param, :wine_app => valid_attributes}, valid_session
        assigns(:wine_app).should eq(wine_app)
      end

      it "redirects to the wine_app" do
        wine_app = WineApp.create! valid_attributes
        put :update, {:id => wine_app.to_param, :wine_app => valid_attributes}, valid_session
        expect(response).to redirect_to(wine_app)
      end
    end

    describe "with invalid params" do
      it "assigns the wine_app as @wine_app" do
        wine_app = WineApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WineApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => wine_app.to_param, :wine_app => { name: nil }}, valid_session
        assigns(:wine_app).should eq(wine_app)
      end

      it "re-renders the 'edit' template" do
        wine_app = WineApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WineApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => wine_app.to_param, :wine_app => { name: nil  }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wine_app" do
      wine_app = WineApp.create! valid_attributes
      expect {
        delete :destroy, {:id => wine_app.to_param}, valid_session
      }.to change(WineApp, :count).by(-1)
    end

    it "redirects to the wine_apps list" do
      wine_app = WineApp.create! valid_attributes
      delete :destroy, {:id => wine_app.to_param}, valid_session
      expect(response).to redirect_to(wine_apps_url)
    end
  end

end
